### ISSUE TITLE
Option to show all pages in the pagination 

### ISSUE THREAD

**Issue by mattab** [matomo-org/github-issues-mirror#11]
Before on issues.piwik.org we could show all pages listed in the pagination control. This is useful in our case, as we want to have a copy of all issues, and also we want google/etc to index all pages. If we use the pagination showing only a few links to pages, Google/etc likely wont index all pages as it requires too many clicks. 

Let's add a new config setting eg. `PAGINATION_COUNT_PAGES_TO_SHOW` which could default to 5 or 10, but in our case we would set it to 100 or 500  (it does not look very pretty of course, but it is functional in having search bots index all content without giving preference to the first pages)

**Comment by Findus23** [comment]
Hi, we can definitly make the number of pages in the pagination configurable (it's already a parameter)

But I'd really recommend you to don't change it to anything >5 as it makes the styling unreadable, and doensn't change anything for search engines:
> Do nothing. Paginated content is very common, and Google does a good job returning the most relevant results to users, regardless of whether content is divided into multiple pages.
[...]
Use rel="next" and rel="prev" links to indicate the relationship between component URLs. This markup provides a strong hint to Google that you would like us to treat these pages as a logical sequence, thus consolidating their linking properties and usually sending searchers to the first page.

We are already using rel=next/prev links so Google should have no problems finding all pages.

from https://support.google.com/webmasters/answer/1663744?hl=en
