### ISSUE TITLE
Error during import daily since Feb 9th with error "Uncaught ArgumentCountError: Too few arguments"

### ISSUE THREAD

**Issue by mattab** [matomo-org/github-issues-mirror#21]
It looks like maybe the import is failing for the last 2 months and getting this error about once a day or so,
although weirdly it worked for weeks at a time in second half of March (or at least we didn't get email errors)

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function Slim\App::__construct(), 0 passed in /home/piwik-issues/github-issues-mirror/src/helpers/SitemapHelper.php on line 18 and at least 1 expected in /home/piwik-issues/github-issues-mirror/src/vendor/slim/slim/Slim/App.php:61

**Comment by sgiehl** [comment]
guess I missed that when updating the app to PHP 8. Will quickly check that.

**Comment by mattab** [comment]
it's probably low priority, but  because we're getting a daily email error, if (and only if) it could be a quick fix then it would be valuable to fix it :sweat_smile:
