### ISSUE TITLE
Track multiple Repos

### ISSUE THREAD

**Issue by jloh** [matomo-org/github-issues-mirror#6]
It'd be cool if you could give this script multiple repos to mirror so you could view say, `http://issues.piwik.org/piwik/1` to view issues for the Piwik project or `http://issues.piwik.org/github-issues-mirror` for the `github-issues-mirror` project.

**Comment by mattab** [comment]
Thank you for your suggestion!

Unfortunately as we won't implement this ourselves, I will close this issue now. (note that if someone really needed this improvement and [contributed](https://developer.matomo.org/guides/contributing-to-piwik-core) a working [Pull Request](https://developer.matomo.org/guides/pull-request-reviews), we would consider likely consider to review, please comment here to discuss further with the team).
